// AUTO-GENERATED from index.css — every non -rgb color variable, grouped
// the same way index.css comments them. This is the single source of truth
// for both the default values AND the list of what's editable in the
// ThemeCustomizer panel. Regenerate this file (don't hand-edit) if index.css
// gains or loses color variables.

const PALETTE_GROUPS = [
  {
    id: "base",
    label: "Base",
    colors: [
      { var: "--white", default: "#ffffff" },
      { var: "--black", default: "#000000" },
    ],
  },
  {
    id: "neutral",
    label: "Neutral",
    colors: [
      { var: "--neutral-50", default: "#fafafa" },
      { var: "--neutral-300", default: "#dddddd" },
      { var: "--neutral-700", default: "#666666" },
    ],
  },
  {
    id: "slate",
    label: "Slate — Primary Neutral",
    colors: [
      { var: "--slate-50", default: "#f8fafc" },
      { var: "--slate-100", default: "#f1f5f9" },
      { var: "--slate-200", default: "#e2e8f0" },
      { var: "--slate-300", default: "#cbd5e1" },
      { var: "--slate-400", default: "#94a3b8" },
      { var: "--slate-500", default: "#64748b" },
      { var: "--slate-600", default: "#475569" },
      { var: "--slate-700", default: "#334155" },
      { var: "--slate-800", default: "#1e293b" },
      { var: "--slate-900", default: "#0f172a" },
      { var: "--slate-950", default: "#020617" },
    ],
  },
  {
    id: "gray",
    label: "Gray — Warm Neutral",
    colors: [
      { var: "--gray-50", default: "#f9fafb" },
      { var: "--gray-100", default: "#f3f4f6" },
      { var: "--gray-200", default: "#e5e7eb" },
      { var: "--gray-300", default: "#d1d5db" },
      { var: "--gray-400", default: "#9ca3af" },
      { var: "--gray-500", default: "#6b7280" },
      { var: "--gray-600", default: "#4b5563" },
      { var: "--gray-700", default: "#374151" },
      { var: "--gray-800", default: "#1f2937" },
      { var: "--gray-900", default: "#111827" },
    ],
  },
  {
    id: "ink",
    label: "Ink — Component Backgrounds",
    colors: [
      { var: "--ink-950", default: "#1e1e28" },
      { var: "--ink-950-b", default: "#202124" },
      { var: "--ink-950-c", default: "#1c1c25" },
      { var: "--ink-950-d", default: "#1a2620" },
      { var: "--ink-950-e", default: "#16161d" },
      { var: "--ink-950-f", default: "#131f18" },
      { var: "--ink-950-g", default: "#111f16" },
      { var: "--ink-950-h", default: "#111916" },
      { var: "--ink-950-i", default: "#0f1a14" },
      { var: "--ink-950-j", default: "#111116" },
      { var: "--ink-950-k", default: "#0e1410" },
      { var: "--ink-950-l", default: "#0c0c0f" },
      { var: "--ink-950-m", default: "#0b0f0d" },
    ],
  },
  {
    id: "blue",
    label: "Blue — Brand Primary",
    colors: [
      { var: "--blue-50", default: "#eff6ff" },
      { var: "--blue-50-b", default: "#fafbff" },
      { var: "--blue-50-c", default: "#f8fbff" },
      { var: "--blue-50-d", default: "#fafbfc" },
      { var: "--blue-50-e", default: "#f5f8ff" },
      { var: "--blue-100", default: "#dbeafe" },
      { var: "--blue-100-b", default: "#f5f7fb" },
      { var: "--blue-100-c", default: "#f4f6fb" },
      { var: "--blue-100-d", default: "#f0f5ff" },
      { var: "--blue-100-e", default: "#eef2ff" },
      { var: "--blue-100-f", default: "#edf2ff" },
      { var: "--blue-100-g", default: "#f5f5f7" },
      { var: "--blue-100-h", default: "#f1f6fb" },
      { var: "--blue-100-i", default: "#f1f3f9" },
      { var: "--blue-100-j", default: "#f0f4f8" },
      { var: "--blue-100-k", default: "#e8f0fe" },
      { var: "--blue-100-l", default: "#eff2f7" },
      { var: "--blue-200", default: "#bfdbfe" },
      { var: "--blue-200-b", default: "#eef1f5" },
      { var: "--blue-200-c", default: "#e0eaff" },
      { var: "--blue-200-d", default: "#e8edf5" },
      { var: "--blue-200-e", default: "#dde8ff" },
      { var: "--blue-200-f", default: "#e8edf3" },
      { var: "--blue-200-g", default: "#e8eaf0" },
      { var: "--blue-200-h", default: "#e2eaf3" },
      { var: "--blue-300", default: "#93c5fd" },
      { var: "--blue-300-b", default: "#c7d2fe" },
      { var: "--blue-300-c", default: "#d6e0ec" },
      { var: "--blue-300-d", default: "#c7d4f8" },
      { var: "--blue-400", default: "#60a5fa" },
      { var: "--blue-400-b", default: "#6ea8ff" },
      { var: "--blue-500", default: "#3b82f6" },
      { var: "--blue-500-b", default: "#635bff" },
      { var: "--blue-500-c", default: "#4f8cff" },
      { var: "--blue-500-d", default: "#8ea3bf" },
      { var: "--blue-500-e", default: "#4f8df7" },
      { var: "--blue-600", default: "#2563eb" },
      { var: "--blue-700", default: "#1d4ed8" },
      { var: "--blue-700-b", default: "#5c7088" },
      { var: "--blue-700-c", default: "#555e7a" },
      { var: "--blue-900", default: "#1a1f71" },
      { var: "--blue-900-b", default: "#163058" },
      { var: "--blue-950", default: "#0f2040" },
      { var: "--blue-950-b", default: "#0f1f38" },
      { var: "--blue-950-c", default: "#0c1a30" },
      { var: "--blue-950-d", default: "#0a1628" },
      { var: "--blue-950-e", default: "#07111f" },
      { var: "--blue-950-f", default: "#060d1a" },
      { var: "--blue-950-g", default: "#050d1a" },
      { var: "--blue-950-h", default: "#030b17" },
    ],
  },
  {
    id: "cyan",
    label: "Cyan — Verification Accent",
    colors: [
      { var: "--cyan-400", default: "#22d3ee" },
      { var: "--cyan-600", default: "#0891b2" },
      { var: "--cyan-800", default: "#007bc1" },
      { var: "--cyan-950", default: "#04141f" },
    ],
  },
  {
    id: "teal",
    label: "Teal — Signup Accent",
    colors: [
      { var: "--teal-400", default: "#2dd4bf" },
      { var: "--teal-500", default: "#14b8a6" },
      { var: "--teal-600", default: "#0d9488" },
    ],
  },
  {
    id: "emerald",
    label: "Emerald",
    colors: [
      { var: "--emerald-100", default: "#d1fae5" },
      { var: "--emerald-200", default: "#a7f3d0" },
      { var: "--emerald-300", default: "#6ee7b7" },
      { var: "--emerald-400", default: "#34d399" },
      { var: "--emerald-500", default: "#10b981" },
      { var: "--emerald-600", default: "#059669" },
      { var: "--emerald-700", default: "#047857" },
      { var: "--emerald-800", default: "#065f46" },
    ],
  },
  {
    id: "green",
    label: "Green — Success",
    colors: [
      { var: "--green-50", default: "#f0fdf4" },
      { var: "--green-100", default: "#dcfce7" },
      { var: "--green-200", default: "#bbf7d0" },
      { var: "--green-400", default: "#4ade80" },
      { var: "--green-500", default: "#22c55e" },
      { var: "--green-600", default: "#16a34a" },
      { var: "--green-700", default: "#15803d" },
      { var: "--green-800", default: "#166534" },
      { var: "--green-800-b", default: "#128a3e" },
    ],
  },
  {
    id: "yellow",
    label: "Yellow",
    colors: [
      { var: "--yellow-500", default: "#facc15" },
    ],
  },
  {
    id: "amber",
    label: "Amber — Warning",
    colors: [
      { var: "--amber-50", default: "#fffbeb" },
      { var: "--amber-100", default: "#fef3c7" },
      { var: "--amber-200", default: "#fde68a" },
      { var: "--amber-300", default: "#fcd34d" },
      { var: "--amber-400", default: "#fbbf24" },
      { var: "--amber-500", default: "#f59e0b" },
      { var: "--amber-600", default: "#d97706" },
      { var: "--amber-700", default: "#b45309" },
      { var: "--amber-800", default: "#92400e" },
    ],
  },
  {
    id: "red",
    label: "Red — Danger",
    colors: [
      { var: "--red-50", default: "#fef2f2" },
      { var: "--red-50-b", default: "#fff5f5" },
      { var: "--red-100", default: "#fee2e2" },
      { var: "--red-200", default: "#fecaca" },
      { var: "--red-300", default: "#fca5a5" },
      { var: "--red-400", default: "#f87171" },
      { var: "--red-500", default: "#ef4444" },
      { var: "--red-600", default: "#dc2626" },
      { var: "--red-700", default: "#b91c1c" },
      { var: "--red-700-b", default: "#eb001b" },
    ],
  },
  {
    id: "rose",
    label: "Rose",
    colors: [
      { var: "--rose-400", default: "#fb7185" },
    ],
  },
  {
    id: "pink",
    label: "Pink",
    colors: [
      { var: "--pink-100", default: "#fce7f3" },
      { var: "--pink-700", default: "#be185d" },
    ],
  },
  {
    id: "purple",
    label: "Purple",
    colors: [
      { var: "--purple-500", default: "#a855f7" },
    ],
  },
  {
    id: "violet",
    label: "Violet — Secondary Accent",
    colors: [
      { var: "--violet-100", default: "#ede9fe" },
      { var: "--violet-400", default: "#a78bfa" },
      { var: "--violet-500", default: "#8b5cf6" },
      { var: "--violet-600", default: "#7c3aed" },
      { var: "--violet-700", default: "#6d28d9" },
    ],
  },
  {
    id: "indigo",
    label: "Indigo",
    colors: [
      { var: "--indigo-100", default: "#f5f3ff" },
      { var: "--indigo-400", default: "#818cf8" },
      { var: "--indigo-600", default: "#4f46e5" },
      { var: "--indigo-700", default: "#4338ca" },
    ],
  },
];

export default PALETTE_GROUPS;